### ISSUE TITLE
由于目标文件夹不存在,无法完成此动作

### ISSUE THREAD

**Issue by guangshao** [leiroc/supercutePSD#1]
运行过程中出现"由于目标文件夹不存在,无法完成此动作" 这样的问题??

**Comment by leiroc** [comment]
请用英文文件名试试

**Comment by leiroc** [comment]
> 运行过程中出现"由于目标文件夹不存在,无法完成此动作" 这样的问题??

此问题已修复，抱歉这么久了。

**Comment by leiroc** [comment]
@guangshao 此问题已解决，抱歉这么久了。
